"use client";

import { useEffect, useRef, useState } from "react";
import "./phone.css";

type Screen = "scan" | "confirm" | "goals" | "research" | "results" | "saved" | "learn" | "safety";
type IconName = "scan" | "arrow" | "back" | "book" | "shield" | "check" | "spark" | "plus" | "close" | "strength" | "brain" | "moon" | "leaf";
const paths: Record<IconName, string> = {
  scan: "M8 3H5a2 2 0 0 0-2 2v3m13-5h3a2 2 0 0 1 2 2v3M3 16v3a2 2 0 0 0 2 2h3m8 0h3a2 2 0 0 0 2-2v-3M7 12h10",
  arrow: "M5 12h14m-6-6 6 6-6 6", back: "M19 12H5m6-6-6 6 6 6", book: "M4 4h6l2 2 2-2h6v16h-6l-2 1-2-1H4V4zm8 2v15", shield: "m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6l8-3zm-4 9 3 3 5-6", check: "m5 12 4 4L19 6", spark: "m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5L12 3z", plus: "M12 5v14M5 12h14", close: "m6 6 12 12M18 6 6 18", strength: "m3 8 5-5m8 18 5-5M5 10l5-5m4 14 5-5M8 8l8 8", brain: "M12 5c-4-5-9 0-6 4-5 1-3 8 1 7-1 5 5 6 5 1V5zm0 0c4-5 9 0 6 4 5 1 3 8-1 7 1 5-5 6-5 1M8 9l4 3m4-3-4 3", moon: "M20 14A9 9 0 0 1 10 3 9 9 0 1 0 20 14z", leaf: "M5 19C-1 5 13 3 21 3c0 9-2 20-14 15m-4 3L16 8",
};
function Icon({ name, size = 22 }: { name: IconName; size?: number }) { return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]} /></svg>; }
function Lumen({ small = false }: { small?: boolean }) { return <svg className={small ? "mp-lumen small" : "mp-lumen"} viewBox="0 0 150 155" aria-hidden="true"><ellipse cx="77" cy="140" rx="43" ry="8" fill="currentColor" opacity=".08" /><path d="m94 96 25 30" stroke="#233d36" strokeWidth="23" strokeLinecap="round" /><path d="m94 96 25 30" stroke="#a5bd78" strokeWidth="14" strokeLinecap="round" /><circle cx="67" cy="64" r="46" fill="#c2d99b" stroke="#233d36" strokeWidth="4" /><circle cx="67" cy="64" r="35" fill="#f4f7dc" stroke="#233d36" strokeWidth="2.5" /><path d="M44 50a24 24 0 0 1 19-12" stroke="#fff" strokeWidth="6" strokeLinecap="round" /><ellipse cx="57" cy="67" rx="3.5" ry="5" fill="#233d36" /><ellipse cx="78" cy="67" rx="3.5" ry="5" fill="#233d36" /><path d="m110 26 3-8 3 8 8 3-8 3-3 8-3-8-8-3z" fill="#edb87c" /><path d="m25 102-3-5m4 15-7 2" stroke="#233d36" strokeWidth="3" strokeLinecap="round" /></svg>; }
function Jar() { return <div className="mp-jar" aria-label="Illustrated sample supplement"><div className="mp-jar-lid" /><span>FIELD NOTES / 001</span><strong>creatine<br />mono.</strong><div>DEMO LABEL <b>3 g</b></div></div>; }
const stages = ["Finding human research", "Reading the methods", "Checking both sides", "Matching your product", "Checking sources & verdicts"];
const baseGoals = ["Muscle strength", "Muscle growth", "Exercise power", "Endurance", "Cognitive function"];
const topics = ["What was promised?", "Human research", "Evidence strength", "Practical benefit", "Product & dose match", "Animal vs human evidence", "Funding & conflicts", "Contradictory findings", "Risks & interactions", "Marketing red flags", "Evidence-based alternatives"];
const initial = { brand: "Sponser", ingredient: "Creatine", form: "Monohydrate", amount: "3", unit: "g", servings: "1" };

export default function MobilePrototype() {
  const [screen, setScreen] = useState<Screen>("scan");
  const [theme, setTheme] = useState("meadow");
  const [product, setProduct] = useState(initial);
  const [confirmed, setConfirmed] = useState(false);
  const [goals, setGoals] = useState(baseGoals);
  const [selected, setSelected] = useState(["Muscle strength", "Muscle growth"]);
  const [custom, setCustom] = useState("");
  const [phase, setPhase] = useState(-1);
  const [paused, setPaused] = useState(false);
  const [saved, setSaved] = useState(false);
  const [showAll, setShowAll] = useState(false);
  const [active, setActive] = useState("Muscle strength");
  const [message, setMessage] = useState("");
  const scroll = useRef<HTMLDivElement>(null);
  const move = (next: Screen) => { setScreen(next); scroll.current?.scrollTo({ top: 0, behavior: "instant" }); setMessage(""); };
  useEffect(() => {
    if (phase < 0 || phase >= 5 || paused) return;
    const timer = setTimeout(() => setPhase((n) => n + 1), 3800);
    return () => clearTimeout(timer);
  }, [phase, paused]);
  const reset = () => { setProduct(initial); setConfirmed(false); setPhase(-1); setPaused(false); setGoals(baseGoals); setSelected(["Muscle strength", "Muscle growth"]); setActive("Muscle strength"); setSaved(false); setShowAll(false); move("scan"); };
  const edit = (key: keyof typeof initial, value: string) => { setProduct((p) => ({ ...p, [key]: value })); setConfirmed(false); setSaved(false); setPhase(0); setMessage("Updated. Demo research restarted for your edits."); };
  const toggle = (goal: string) => setSelected((s) => s.includes(goal) ? s.filter((x) => x !== goal) : [...s, goal]);
  const visible = showAll ? goals : selected;
  const current = visible.includes(active) ? active : visible[0];
  const milestone = screen === "confirm" ? 0 : screen === "goals" ? 1 : screen === "research" ? 2 : 3;
  const renderProgress = () => <div className="mp-live" role="status"><span className="mp-live-dot" /><div><strong>{phase >= 5 ? "Demo research ready" : "Research has a head start"}</strong><span>{phase >= 5 ? "Simulated • no live searches" : `${stages[Math.max(0, phase)]} · simulated`}</span></div></div>;
  const renderRings = () => <div className="mp-score"><div className="mp-score-plot" role="img" aria-label="Four illustrative rings; no numeric assessment"><svg viewBox="0 0 250 250" aria-hidden="true">{[108, 91, 74, 57].map((r, i) => <g key={r}><circle cx="125" cy="125" r={r} fill="none" stroke="var(--mp-track)" strokeWidth="10" /><circle cx="125" cy="125" r={r} fill="none" stroke={["var(--mp-r1)", "var(--mp-r2)", "var(--mp-r3)", "var(--mp-r4)"][i]} strokeWidth="10" strokeLinecap="round" strokeDasharray={`${2 * Math.PI * r * [0.83, 0.73, 0.64, 0.78][i]} ${2 * Math.PI * r}`} transform="rotate(-90 125 125)" /></g>)}</svg><div><strong>—</strong><span>Demo score</span></div></div><div className="mp-ring-labels">{["Effect", "Form", "Dose", "Evidence"].map((name, i) => <div key={name}><i style={{ background: `var(--mp-r${i + 1})` }} /><span>{name}</span><b>—</b></div>)}</div></div>;
  const safety = <button className="mp-safety-card" onClick={() => move("safety")}><Icon name="shield" /><div><strong>Safety comes first</strong><span>No safety assessment in this demo.</span></div><Icon name="arrow" size={18} /></button>;
  const begin = () => { setPhase(0); setConfirmed(false); move("confirm"); };

  return <main id="main-content" className={`mp-stage mp-${theme}`}><aside className="mp-desktop-note"><a href="/design-lab/">← Earlier concepts</a><span className="mp-kicker">BS PROOF / MOBILE DESIGN STUDY</span><h1>Small screen.<br /><em>Big clarity.</em></h1><p>Meet Field Notebook.<br />A lighter, friendlier way to follow the evidence.</p><div className="mp-design-points"><span><Icon name="check" /> Thumb-friendly by design</span><span><Icon name="check" /> Playful about the process</span><span><Icon name="check" /> Serious about uncertainty</span></div><div className="mp-theme-choice" aria-label="Color theme">{["meadow", "slate"].map((t) => <button key={t} aria-pressed={theme === t} onClick={() => setTheme(t)}><i className={t} />{t === "meadow" ? "Meadow" : "Slate"}</button>)}</div><p className="mp-credit">Design direction: Claude Fable 5.1<br />Interactive implementation: local prototype<br />No backend, real research, or health scores.</p><button className="mp-reset" onClick={reset}>Restart demo ↻</button></aside>
  <div className="mp-device"><div className="mp-system" aria-hidden="true"><b>9:41</b><span className="mp-island" /><span>▮▮▮  ▰</span></div><div className="mp-simulation"><span>INTERACTIVE DEMO</span><button onClick={() => setTheme(theme === "meadow" ? "slate" : "meadow")}>{theme === "meadow" ? "Dark theme" : "Light theme"}</button></div><div className="mp-phone-scroll" ref={scroll}><header className="mp-app-header"><button className="mp-brand" onClick={() => move("scan")}>bs<span>proof</span><i /></button><button className="mp-icon-button" aria-label="Safety information" onClick={() => move("safety")}><Icon name="shield" /></button></header>
  {["confirm", "goals", "research", "results"].includes(screen) && <div className="mp-milestones" aria-label="Your research journey">{["Label", "Interests", "Research", "Report"].map((label, i) => <div key={label} className={i <= milestone ? "reached" : ""}><span>{i < milestone ? <Icon name="check" size={14} /> : i + 1}</span><small>{label}</small></div>)}</div>}
  {message && <p className="mp-toast" role="status">{message}</p>}
  <div className="mp-screen" key={screen}>
  {screen === "scan" && <><div className="mp-greeting"><span className="mp-kicker">A LITTLE CURIOSITY. A LOT MORE CLARITY.</span><h2>What’s really<br />in your <em>routine?</em></h2><p>Less label hype. More understanding.<br />Let’s take a closer look.</p></div><button className="mp-scan-scene" onClick={begin} aria-label="Start with the demo label"><span className="mp-scene-tag"><Icon name="scan" size={16} /> UNDER THE LENS</span><div className="mp-scan-corners"><Jar /></div><Lumen /><span className="mp-sticker">follow the<br /><b>evidence.</b></span></button><button className="mp-cta" onClick={begin}><Icon name="scan" />Try a sample scan <Icon name="arrow" /></button><p className="mp-centered-note">Demo bottle only. No camera or upload is used.</p><div className="mp-mini-title"><h3>Your curiosity, guided.</h3><span>3 small steps</span></div><div className="mp-how"><div><span>01</span><strong>Check the label</strong><p>You confirm the facts.</p></div><div><span>02</span><strong>Pick your interests</strong><p>We keep the full picture.</p></div><div><span>03</span><strong>Explore the evidence</strong><p>The answer, and its limits.</p></div></div><button className="mp-learn-link" onClick={() => move("learn")}><Icon name="book" /><span>What makes a good study?</span><Icon name="arrow" /></button></>}
  {screen === "confirm" && <><span className="mp-kicker">STEP 01 · CHECK THE DETAILS</span><h2>First, <em>the facts.</em></h2><p>Here’s what the sample label says.<br />You’re in charge of the final details.</p><div className="mp-product-mini"><div className="mp-mini-jar"><Jar /></div><div><span className="mp-pill">SAMPLE LABEL</span><strong>{product.ingredient || "Ingredient unknown"}</strong><small>{product.form || "Form not stated"}</small></div><span className="mp-stamp">READ<br />CHECK</span></div><form onSubmit={(e) => { e.preventDefault(); setConfirmed(true); move("goals"); }}><div className="mp-form-grid">{([['brand','Brand'],['ingredient','Supplement'],['form','Form'],['amount','Per-serving amount'],['unit','Unit'],['servings','Servings per day']] as const).map(([key, label]) => <label key={key} className={key === "amount" || key === "unit" ? "half" : ""}>{label}{key === "unit" ? <select value={product.unit} onChange={(e) => edit(key,e.target.value)}><option>g</option><option>mg</option><option value="">Unknown</option></select> : <input value={product[key]} onChange={(e) => edit(key,e.target.value)} inputMode={key === "amount" || key === "servings" ? "decimal" : undefined} placeholder="Not stated" />}</label>)}</div><p className="mp-helper"><Icon name="leaf" size={18} />Blank beats a guess. Leave missing details empty.</p>{renderProgress()}<button className="mp-cta" type="submit">That’s my product <Icon name="check" /></button></form></>}
  {screen === "goals" && <><span className="mp-kicker">STEP 02 · MAKE IT YOURS</span><h2>What are you<br /><em>curious about?</em></h2><p>Pick what matters. We’ll put it first.<br />Research still covers all listed outcomes.</p><div className="mp-goals">{goals.map((g,i) => <button key={g} aria-pressed={selected.includes(g)} onClick={() => toggle(g)}><span className={`mp-goal-art art-${i % 4}`}><Icon name={(["strength","leaf","spark","moon","brain"] as IconName[])[i % 5]} size={30} /></span><strong>{g}</strong><span className="mp-check-box">{selected.includes(g) && <Icon name="check" size={14} />}</span></button>)}</div><form className="mp-custom" onSubmit={(e) => { e.preventDefault(); const v = custom.trim(); if(v && !goals.some((g) => g.toLowerCase() === v.toLowerCase())) { setGoals([...goals,v]); setSelected([...selected,v]); setPhase(0); } setCustom(""); }}><input aria-label="Another outcome" placeholder="Something else?" value={custom} maxLength={60} onChange={(e) => setCustom(e.target.value)} /><button aria-label="Add outcome"><Icon name="plus" /></button></form><div className="mp-choice-count"><span>{selected.length} interests picked</span><button onClick={() => setSelected([...goals])}>Choose all</button></div>{renderProgress()}<button className="mp-cta" disabled={!selected.length} onClick={() => move("research")}>Follow the research <Icon name="arrow" /></button><button className="mp-quiet" onClick={() => move("confirm")}><Icon name="back" size={18} />Edit my product</button></>}
  {screen === "research" && <><div className="mp-research-hero"><Lumen /><span className="mp-floating-note">both sides,<br /><b>always.</b></span></div><span className="mp-kicker">STEP 03 · FOLLOWING THE EVIDENCE</span><h2>{phase >= 5 ? <>Ready to <em>explore.</em></> : <>Curiosity <em>at work.</em></>}</h2><p>{phase >= 5 ? "Your sample report is ready to explore." : "We look at what supports the claim. And what challenges it."}</p><div className="mp-research-card"><div className="mp-card-heading"><span>Research trail</span><b>{Math.max(0,phase)} / 5</b></div><ol>{stages.map((s,i) => <li key={s} className={i < phase ? "complete" : i === phase ? "active" : ""}><span>{i < phase ? <Icon name="check" size={16} /> : i+1}</span><div><strong>{s}</strong>{i === phase && <small>Current simulated stage</small>}</div></li>)}</ol></div><div className="mp-demo-note">Simulated progress. No studies are being searched or read in this prototype.</div><div className="mp-inline-actions"><button onClick={() => setPaused((p) => !p)}>{paused ? "Resume demo" : "Pause demo"}</button><button onClick={() => { setPhase(5); move("results"); }}>Skip demo wait →</button></div>{phase >= 5 && <button className="mp-cta" onClick={() => move("results")}>Open my field notes <Icon name="book" /></button>}<button className="mp-curiosity-card" onClick={() => move("learn")}><Icon name="spark" /><div><strong>While you’re curious…</strong><span>No evidence ≠ evidence of no benefit.</span></div><Icon name="arrow" size={18} /></button></>}
  {screen === "results" && <><div className="mp-report-heading"><span className="mp-pill">YOUR FIELD NOTES · DEMO</span><h2>The bigger<br /><em>picture.</em></h2><p>{product.ingredient || "Supplement unknown"} · {product.form || "Form unknown"}</p><button className="mp-edit-product" onClick={() => { setConfirmed(false); move("confirm"); }}>Edit product</button></div>{safety}<div className="mp-outcome-tabs" aria-label="Displayed outcomes">{visible.map((g) => <button key={g} aria-pressed={current===g} onClick={() => setActive(g)}>{g}</button>)}</div><article className="mp-result-card"><div className="mp-card-heading"><span>OUTCOME / {current}</span><Icon name="spark" size={18} /></div>{renderRings()}<span className="mp-pill">ILLUSTRATIVE · NOT ASSESSED</span><h3>The verdict lives here.<br />So does the uncertainty.</h3><p>In a real report, you’ll see what the research suggests and how well it fits this product.</p><div className="mp-limit"><strong>The important bit</strong><p>Decorative rings are not findings. No number, efficacy conclusion or source count has been calculated.</p></div><details className="mp-report-details"><summary>Open the full research report <Icon name="plus" size={18} /></summary>{topics.map((t,i) => <div key={t}><strong>{String(i+1).padStart(2,"0")} · {t}</strong><p>Not assessed in this prototype. The live report will include supporting sources and limitations.</p></div>)}</details><button className="mp-method-link" onClick={() => move("learn")}><Icon name="book" size={18} /> How to read the four rings <Icon name="arrow" size={16} /></button></article><button className="mp-quiet" onClick={() => setShowAll((s) => !s)}>{showAll ? "Show only my interests" : `Explore all ${goals.length} outcomes`} <Icon name="arrow" size={18} /></button><button className="mp-cta" onClick={() => { setSaved(true); setMessage("Sample report saved for this browser session."); }}><Icon name={saved ? "check" : "book"} />{saved ? "Saved to your field notes" : "Save sample report"}</button><button className="mp-quiet" onClick={() => move("goals")}>Change my interests</button><p className="mp-centered-note">AI research is not medical advice.<br />This design preview contains no actual research.</p></>}
  {screen === "saved" && <><span className="mp-kicker">YOUR FIELD NOTES</span><h2>A little more<br /><em>understanding.</em></h2><p>Your research, kept close.</p>{saved ? <button className="mp-saved-card" onClick={() => move("results")}><span className="mp-goal-art art-0"><Icon name="book" size={28} /></span><div><strong>{product.ingredient || "Sample supplement"}</strong><span>{selected.length} selected outcomes · demo</span></div><Icon name="arrow" /></button> : <div className="mp-empty"><Lumen /><h3>Your notebook is open.</h3><p>Try a sample scan, then save the report here. Nothing is stored beyond this session.</p><button className="mp-cta" onClick={begin}>Explore a sample <Icon name="arrow" /></button></div>}</>}
  {screen === "learn" && <><span className="mp-kicker">CURIOUS IS A GOOD PLACE TO START</span><h2>Small lessons.<br /><em>Sharper questions.</em></h2><p>No health points. Just a clearer picture.</p>{[{title:"Evidence is not a popularity contest.",text:"Several reviews can include the same trials. More links don’t automatically mean stronger evidence.",icon:"book"},{title:"A dose is more than a number.",text:"Daily amount, preparation, population and duration all matter. A larger dose is not automatically better.",icon:"leaf"},{title:"Unknown is an honest answer.",text:"Missing evidence does not prove a product fails. A high-certainty conclusion can also be that there is little benefit.",icon:"brain"}].map((x,i) => <details className="mp-lesson" key={x.title}><summary><span className={`mp-goal-art art-${i}`}><Icon name={x.icon as IconName} /></span><strong>{x.title}</strong><Icon name="plus" size={18} /></summary><p>{x.text}</p></details>)}<div className="mp-info"><strong>The four-ring idea</strong><p>Effect: what the findings suggest.<br />Form: applicability to this preparation.<br />Dose: match to studied regimens.<br />Evidence: certainty in the conclusion.</p><p>The numerical rubric is not finalized. All rings in this prototype are decorative.</p></div>{confirmed && <button className="mp-cta" onClick={() => move(phase>=5 ? "results" : "research")}>Back to my research <Icon name="arrow" /></button>}</>}
  {screen === "safety" && <><span className="mp-kicker">ALWAYS PART OF THE PICTURE</span><h2>Benefit isn’t<br /><em>the whole story.</em></h2><div className="mp-safety-hero"><Icon name="shield" size={64} /></div><div className="mp-info"><strong>No safety assessment has been performed.</strong><p>This is a design prototype. It cannot tell you whether a supplement is safe or compatible with your medication.</p><p>In the real app, relevant warnings will remain visible whatever outcomes you select. A positive benefit score will never cancel a safety warning.</p></div><button className="mp-cta" onClick={() => move(confirmed ? phase>=5 ? "results" : "research" : "scan")}>Back to exploring <Icon name="arrow" /></button></>}
  </div><div className="mp-content-end" /></div><nav className="mp-bottom-nav" aria-label="Main navigation">{([{name:"scan",label:"Explore",icon:"scan"},{name:"saved",label:"My notes",icon:"book"},{name:"learn",label:"Learn",icon:"spark"},{name:"safety",label:"Safety",icon:"shield"}] as const).map((n) => <button key={n.name} aria-current={screen===n.name || n.name === "scan" && ["confirm","goals","research","results"].includes(screen) ? "page" : undefined} onClick={() => move(n.name === "scan" && confirmed ? phase>=5 ? "results" : "research" : n.name)}><span><Icon name={n.icon} /></span><small>{n.label}</small></button>)}</nav><div className="mp-home-indicator" aria-hidden="true"><span /></div></div><aside className="mp-preview-controls"><span className="mp-kicker">TAKE A LOOK AROUND</span><h3>One journey.<br />Six little moments.</h3>{([['scan','01','A spark of curiosity'],['confirm','02','The facts, confirmed'],['goals','03','Make it yours'],['research','04','Follow the trail'],['results','05','The bigger picture'],['learn','06','Learn a little']] as const).map(([s,n,t]) => <button key={s} onClick={() => { if(["goals","research","results"].includes(s)) setConfirmed(true); if(s==="research") setPhase(0); if(s==="results") setPhase(5); if(s==="confirm") setPhase(0); move(s); }} aria-pressed={screen===s}><span>{n}</span>{t}<Icon name="arrow" size={16} /></button>)}<p>390px phone canvas<br />Switch screens or tap through the app.<br />All data is simulated.</p></aside></main>;
}
