export const RESEARCH_COPY = {
  en: {
    title: "Live research · experimental/unvalidated", queued: "Queued for the private research worker.", running: "Research is running.", succeeded: "Research audit returned.", failed: "Research did not complete.", disabled: "Live research is off on this deployment; research was not assessed.", unavailable: "Live research is temporarily unavailable; research was not assessed.", startFailed: "Could not start live research; research was not assessed.", retry: "Check or resume research", outcome: "Outcome", basis: "Audit finding", model: "Model", prompt: "Prompt version", provenance: "Server provenance", evidenceStatus: "Evidence status", affectsScore: "Changes scan score", yes: "yes", no: "no", notAffectScore: "This audit does not change the retained scan score.", summaryLabels: { requests: "requests", errors: "errors", walls: "walls", refusals: "refusals", search_snippets: "search snippets", fetch_summaries: "fetch summaries", original_documents: "original documents" }, runner: "Runner", access: "Source access summary", inventory: "Inventory access", couldNotAccess: "Could not access", modelTextNote: "Model-written research text is shown in English (untranslated).", notScored: "not scored", noId: "This scan has no verified saved run ID; live research was not started.", auth: "Sign in to view private live research.", error: "Research status could not be loaded; research was not assessed.", busy: "The research worker is busy. Try again later; research was not assessed.", notResearchable: "This saved scan is not eligible for live research; research was not assessed.", failureCode: "Failure code", sourceLimitations: "Limitations"
  },
  lt: {
    title: "Tiesioginis tyrimas · eksperimentinis / nepatvirtintas", queued: "Laukia privačios tyrimų užduoties.", running: "Tyrimas vykdomas.", succeeded: "Gautas tyrimo auditas.", failed: "Tyrimas nebaigtas.", disabled: "Šiame diegime tiesioginis tyrimas išjungtas; tyrimas nevertintas.", unavailable: "Tiesioginis tyrimas laikinai nepasiekiamas; tyrimas nevertintas.", startFailed: "Tiesioginio tyrimo pradėti nepavyko; tyrimas nevertintas.", retry: "Patikrinti arba tęsti tyrimą", outcome: "Rezultatas", basis: "Audito išvada", model: "Modelis", prompt: "Užklausos versija", provenance: "Serverio kilmės duomenys", evidenceStatus: "Įrodymų būsena", affectsScore: "Keičia skenavimo balą", yes: "taip", no: "ne", notAffectScore: "Šis auditas nekeičia išsaugoto skenavimo balo.", summaryLabels: { requests: "užklausos", errors: "klaidos", walls: "prieigos blokavimai", refusals: "atsisakymai", search_snippets: "paieškos ištraukos", fetch_summaries: "gautų puslapių santraukos", original_documents: "originalūs dokumentai" }, runner: "Vykdytojas", access: "Šaltinių prieigos suvestinė", inventory: "Inventoriaus prieiga", couldNotAccess: "Nepavyko pasiekti", modelTextNote: "Modelio parašytas tyrimo tekstas rodomas anglų kalba (neišverstas).", notScored: "neįvertinta", noId: "Šis skenavimas neturi patvirtinto išsaugoto vykdymo ID; tiesioginis tyrimas nepradėtas.", auth: "Prisijunkite, kad matytumėte privatų tiesioginį tyrimą.", error: "Nepavyko gauti tyrimo būsenos; tyrimas nevertintas.", busy: "Tyrimų vykdytojas užimtas. Bandykite vėliau; tyrimas nevertintas.", notResearchable: "Šis išsaugotas skenavimas netinka tiesioginiam tyrimui; tyrimas nevertintas.", failureCode: "Nesėkmės kodas", sourceLimitations: "Apribojimai"
  }
} as const;
export type ResearchLanguage = keyof typeof RESEARCH_COPY;
export type ResearchCopy = typeof RESEARCH_COPY[ResearchLanguage];
