"use client";

import { useEffect, useState } from "react";
import "./prototype.css";

type Layout = "guided" | "workspace" | "conversation";
const layouts: { id: Layout; name: string; subtitle: string }[] = [
  { id: "guided", name: "A · Guided", subtitle: "One considered step at a time" },
  { id: "workspace", name: "B · Workspace", subtitle: "Everything in view" },
  { id: "conversation", name: "C · Conversation", subtitle: "A little guidance goes a long way" },
];
const initialOutcomes = ["Muscle strength", "Muscle growth", "Exercise power", "Endurance", "Cognitive function"];
const phases = ["Finding relevant human research", "Opening reviews and clinical trials", "Checking conflicting findings", "Comparing your form and dose", "Validating the research assessment"];
const fields = ["Brand", "Supplement", "Form", "Amount per serving", "Unit", "Servings per day"] as const;
const demoProduct = { Brand: "Sponser", Supplement: "Creatine", Form: "Monohydrate", "Amount per serving": "3", Unit: "g", "Servings per day": "1" };
const questions = ["What exactly is promised?", "What human research supports it?", "How strong is the evidence?", "Would the benefit be noticeable?", "Does this research match your product?", "Is any evidence only animal or laboratory research?", "Who funded the research?", "What findings contradict the claim?", "What risks and interactions are known?", "Are there misleading marketing signals?", "Are there evidence-based alternatives?"];

function Bottle() {
  return <div className="dl-bottle-scene" aria-label="Illustration of a fictional sample supplement"><div className="dl-orbit" /><div className="dl-bottle"><div className="dl-lid" /><div className="dl-bottle-label"><span>THE DAILY STANDARD</span><strong>creatine<br />monohydrate.</strong><i>Pure. Simple. Studied.</i><div>DEMO PRODUCT <b>300 g</b></div></div></div><span className="dl-photo-note">ILLUSTRATIVE PACKAGING</span></div>;
}

function Rings({ alternate = false }: { alternate?: boolean }) {
  return <div className="dl-rings" role="img" aria-label="Four decorative demo rings; no research score calculated"><svg viewBox="0 0 260 260" aria-hidden="true">{[112, 94, 76, 58].map((r, i) => <g key={r}><circle cx="130" cy="130" r={r} fill="none" stroke="#e8e9dd" strokeWidth="11" /><circle cx="130" cy="130" r={r} fill="none" stroke={["#34604b", "#78956d", "#a8b67c", "#c8a35d"][i]} strokeWidth="11" strokeLinecap="round" strokeDasharray={`${2 * Math.PI * r * ([0.79, 0.88, 0.67, 0.75][i] - (alternate ? 0.14 : 0))} ${2 * Math.PI * r}`} transform="rotate(-90 130 130)" /></g>)}</svg><div><strong>—</strong><span>/ 100</span><small>DEMO ONLY</small></div></div>;
}

export default function DesignLab() {
  const [layout, setLayout] = useState<Layout>("guided");
  const [step, setStep] = useState(0);
  const [product, setProduct] = useState(demoProduct);
  const [confirmed, setConfirmed] = useState(false);
  const [outcomes, setOutcomes] = useState(initialOutcomes);
  const [selected, setSelected] = useState(["Muscle strength", "Muscle growth"]);
  const [custom, setCustom] = useState("");
  const [phase, setPhase] = useState(0);
  const [showAll, setShowAll] = useState(false);
  const [notice, setNotice] = useState("");

  useEffect(() => {
    if (step === 3 || phase >= phases.length) return;
    const timer = setTimeout(() => setPhase((p) => p + 1), 4500);
    return () => clearTimeout(timer);
  }, [phase, step]);

  const changeProduct = (field: typeof fields[number], value: string) => {
    setProduct((p) => ({ ...p, [field]: value }));
    setConfirmed(false);
    setPhase(0);
    setNotice("Product changed. The demo research has restarted; previous assessments are discarded.");
  };
  const confirm = () => {
    setConfirmed(true);
    setNotice("");
    setStep(1);
  };
  const toggle = (outcome: string) => setSelected((s) => s.includes(outcome) ? s.filter((x) => x !== outcome) : [...s, outcome]);
  const restart = () => { setStep(0); setPhase(0); setConfirmed(false); setNotice(""); setShowAll(false); setProduct(demoProduct); setOutcomes(initialOutcomes); setSelected(["Muscle strength", "Muscle growth"]); setCustom(""); };
  const research = <div className="dl-research"><div className="dl-label"><span className={phase < phases.length ? "dl-pulse" : ""} />{phase < phases.length ? "DEMO RESEARCH IN PROGRESS" : "DEMO RESEARCH COMPLETE"}</div><h3>{phase < phases.length ? phases[phase] : "Your research is ready."}</h3><p>Simulated activity for this prototype. No searches or model calls are running.</p><ol>{phases.map((text, i) => <li key={text} className={i < phase ? "done" : i === phase ? "current" : ""}><span>{i < phase ? "✓" : `0${i + 1}`}</span>{text}</li>)}</ol><div className="dl-research-foot"><span>{phase < phases.length ? "Looking beyond the marketing." : "All demo stages complete."}</span><b>{Math.min(phase, 5)} / 5 stages</b></div></div>;

  const confirmation = <section className="dl-confirm"><div className="dl-section-heading"><span className="dl-label">01 / YOUR PRODUCT</span><h2>First, the facts.</h2><p>A good answer starts with the right label.<br />Check what we read. Everything is editable.</p></div><div className="dl-product-form">{fields.map((field) => <label key={field}>{field}<input value={product[field]} onChange={(e) => changeProduct(field, e.target.value)} inputMode={field === "Amount per serving" || field === "Servings per day" ? "decimal" : undefined} placeholder="Not known" /></label>)}</div><div className="dl-fact-note">↳ Not on the label? Leave it blank. We won’t guess your daily dose.</div><button className="dl-primary" onClick={confirm}>Confirm product <span>→</span></button><div className="dl-privacy">Local demo · Edits stay in this browser session</div></section>;

  const interests = <section><div className="dl-section-heading"><span className="dl-label">02 / YOUR INTERESTS</span><h2>What matters<br />to you?</h2><p>We research the whole picture.<br />You choose what comes to the front.</p></div><div className="dl-outcome-options">{outcomes.map((o, i) => <button key={o} aria-pressed={selected.includes(o)} onClick={() => toggle(o)} className={selected.includes(o) ? "chosen" : ""}><span className="dl-option-icon">{["↗", "◒", "ϟ", "↻", "◎"][i % 5]}</span><span>{o}</span><b>{selected.includes(o) ? "✓" : "+"}</b></button>)}</div><form className="dl-add" onSubmit={(e) => { e.preventDefault(); const value = custom.trim(); if (value && !outcomes.some((o) => o.toLowerCase() === value.toLowerCase())) { setOutcomes((o) => [...o, value]); setSelected((s) => [...s, value]); setPhase(0); } setCustom(""); }}><input aria-label="Add another outcome" placeholder="Something else? Add an outcome" value={custom} onChange={(e) => setCustom(e.target.value)} maxLength={80} /><button type="submit" aria-label="Add outcome">+</button></form><div className="dl-selection-row"><button className="dl-text-button" onClick={() => setSelected([...outcomes])}>Select all outcomes</button><span>{selected.length} selected</span></div><button className="dl-primary" disabled={!selected.length} onClick={() => setStep(2)}>Continue to research <span>→</span></button><div className="dl-privacy">Your choices filter the results. Not the evidence.</div></section>;

  const results = <section className="dl-results"><div className="dl-result-top"><div><span className="dl-label">THE FULL PICTURE / DEMO RESULTS</span><h2>Less guesswork.<br /><em>More perspective.</em></h2></div><button className="dl-secondary" onClick={() => { setStep(1); setShowAll(false); }}>Change interests ↗</button></div><div className="dl-product-strip"><span className="dl-mini-mark">↗</span><div><strong>{product.Brand || "Brand unknown"} · {product.Supplement || "Supplement unknown"}</strong><small>{product.Form || "Form unknown"} · {product["Amount per serving"] || "Unknown amount"} {product.Unit} per serving · {product["Servings per day"] || "Unknown"} servings/day</small></div><button className="dl-text-button" onClick={() => { setStep(0); setConfirmed(false); }}>Edit</button></div><div className="dl-demo-disclaimer">DESIGN PREVIEW — All rings and report text below are illustrative. No efficacy, safety or numeric assessment has been performed.</div><div className="dl-result-grid">{(showAll ? outcomes : selected).map((outcome, i) => <article className="dl-result-card" key={outcome}><div className="dl-card-kicker"><span>OUTCOME / {String(i + 1).padStart(2, "0")}</span><span className="dl-tag">Sample layout</span></div><h3>{outcome}</h3><Rings alternate={i % 2 === 1} /><h4>Your evidence-backed verdict goes here.</h4><p>A short explanation of the findings, followed by the most important limitation for your product.</p><div className="dl-ring-legend">{["Effect", "Form", "Dose", "Evidence"].map((label, j) => <div key={label}><i style={{ background: ["#34604b", "#78956d", "#a8b67c", "#c8a35d"][j] }} /><span>{label}</span><b>—</b></div>)}</div><details><summary>Explore the research <span>+</span></summary><div className="dl-report"><p>In the live product, every section below will carry findings, limitations and checked sources.</p>{questions.map((q, n) => <div key={q}><strong>{n + 1}. {q}</strong><p>Not assessed in this design prototype.</p></div>)}</div></details></article>)}</div><button className="dl-secondary dl-show-all" onClick={() => setShowAll((v) => !v)}>{showAll ? "Show my selected outcomes" : `Show all ${outcomes.length} researched outcomes`} <span>↗</span></button><aside className="dl-safety"><span>!</span><div><strong>Safety doesn’t disappear when you filter.</strong><p>This is where verified cautions and interactions will appear, regardless of your selected outcomes. No safety assessment has been made in this demo.</p></div></aside><p className="dl-result-note">AI research assessment · Sources and scoring method will be inspectable · Not medical advice</p></section>;

  const waiting = <section className="dl-waiting"><span className="dl-label">03 / LOOKING CLOSER</span><h2>Good questions<br />deserve <em>real research.</em></h2><p>Not just what supports the claim.<br />What challenges it, too.</p>{research}<button className="dl-primary" onClick={() => { setPhase(5); setStep(3); }}>{phase < 5 ? "Skip demo wait · Preview results" : "See my results"}<span>→</span></button><button className="dl-text-button" onClick={() => setStep(1)}>← Change my interests</button></section>;

  return <main id="main-content" className={`dl dl-${layout}`}><div className="dl-toolbar"><div><span className="dl-lab-dot" /> DESIGN LAB <small>Local prototype · No live research</small></div><div className="dl-layout-switch" aria-label="Choose design">{layouts.map((l) => <button aria-pressed={layout === l.id} key={l.id} onClick={() => setLayout(l.id)}>{l.name}</button>)}</div><button className="dl-text-button" onClick={restart}>Restart ↻</button></div><div className="dl-shell"><header className="dl-masthead"><a href="/design-lab" className="dl-brand">bs<span>proof</span><i>®</i></a><span>YOUR SUPPLEMENT. UNDER THE LENS.</span><span className="dl-edition">CONCEPT {layout === "guided" ? "01" : layout === "workspace" ? "02" : "03"}</span></header><div className="dl-step-nav" aria-label="Prototype screens">{["Confirm product", "Your outcomes", "Research", "Results"].map((s, i) => <button key={s} aria-current={step === i ? "step" : undefined} disabled={i > 0 && !confirmed} onClick={() => setStep(i)}><span>{String(i + 1).padStart(2, "0")}</span>{s}</button>)}</div>{notice && <p className="dl-notice" role="status">{notice}</p>}
    {step === 3 ? results : layout === "guided" ? <div className="dl-guided-grid"><aside className="dl-editorial"><span className="dl-label">A LITTLE CLARITY GOES A LONG WAY.</span><h1>Beyond<br />the <em>label.</em></h1><Bottle /><div className="dl-editorial-bottom"><span>01 — READ THE LABEL<br />02 — FOLLOW THE EVIDENCE</span><span>↓</span></div></aside><div className="dl-guided-content">{step === 0 ? confirmation : step === 1 ? interests : waiting}{step < 2 && <div className="dl-background-status" role="status"><span className="dl-pulse" /><div><strong>{phase < 5 ? "Already looking into it." : "Demo research ready."}</strong><small>{phases[Math.min(phase, 4)]} · simulated</small></div></div>}</div></div> : layout === "workspace" ? <><div className="dl-workspace-heading"><span className="dl-label">YOUR PERSONAL RESEARCH DESK</span><h1>The facts.<br /><em>In full view.</em></h1><p>Refine your product on the left.<br />Follow the evidence on the right.</p></div><div className="dl-workspace-grid"><div className="dl-panel">{confirmation}</div><aside className="dl-panel dl-panel-dark">{research}<div className="dl-research-memo">WE LOOK BOTH WAYS.<p>Positive findings. Null results. Conflicting evidence. Nothing cherry-picked.</p></div></aside><div className="dl-panel dl-workspace-interests">{confirmed ? step === 2 ? waiting : interests : <><span className="dl-label">UP NEXT / YOUR OUTCOMES</span><h3>Your interests, not a filter on the science.</h3><p>Confirm the product above to choose which results you’ll see.</p></>}</div></div></> : <div className="dl-chat-grid"><aside><span className="dl-label">A GUIDED SECOND OPINION</span><h1>Let’s look<br /><em>closer.</em></h1><Bottle /><p>Not another marketing claim.<br />An explanation you can inspect.</p></aside><section className="dl-chat"><div className="dl-assistant"><span className="dl-avatar">b.</span><div><strong>BS Proof <small>Research assistant · demo</small></strong><p>{step === 0 ? "I’ve read the sample label. Before we go further, does this look like your product? I’m already starting the research in the background." : step === 1 ? `Thanks. We’re looking at ${product.Brand} ${product.Supplement}. Which outcomes would you like me to put first?` : "I’m checking the research from both directions. You can follow each stage below."}</p></div></div>{step > 0 && <div className="dl-user-bubble">Confirmed: {product.Supplement}, {product.Form}, {product["Amount per serving"]} {product.Unit} per serving. ✓</div>}<div className="dl-chat-card">{step === 0 ? confirmation : step === 1 ? interests : waiting}</div><div className="dl-chat-foot"><span className="dl-pulse" />{phase < 5 ? "Demo research continues while we talk." : "Demo research complete."}</div></section></div>}
    <footer className="dl-footer"><span>CLARITY OVER CLAIMS.</span><span>{layouts.find((l) => l.id === layout)?.subtitle}</span><span>BS PROOF / DESIGN STUDY</span></footer></div></main>;
}
