-- BS-PROOF scan-run history. Run once in Supabase: SQL Editor -> New query.
-- Idempotent: every statement is safe to re-run (create ... if not exists,
-- insert ... on conflict do nothing).
--
-- What this is for: POST /api/scan writes one row per ACCEPTED manual or
-- photo run (lib/scan-history/store.ts) so the owner can inspect what the
-- product actually answered, later, for a specific run. It is written with
-- the SERVICE ROLE key from the server only -- never from a browser -- and
-- there is deliberately no read policy and no public/read endpoint anywhere
-- in the app. Reading this data back is a job for the Supabase SQL editor (or
-- a future owner-only tool), not this app.
--
-- Five decisions worth keeping, none of them cosmetic:
--
-- 1. A PRIVATE storage bucket for photos, never the database. `scan_runs`
--    stores the bucket name, the object path, the MIME type, the byte count
--    and a SHA-256 -- never base64, never the bytes. Storage is for bytes;
--    Postgres is for facts about them.
--
-- 2. RLS ON everywhere, no anon policies -- identical discipline to
--    docs/waitlist.sql. The API writes with the SERVICE ROLE key, which
--    bypasses RLS; nothing else (the anon key, a browser, PostgREST's default
--    role) can read, write or list a single row or a single object.
--
-- 3. The run id is generated by the app BEFORE analysis (crypto.randomUUID)
--    and reused as both the primary key and the storage path prefix, so a row
--    and its image can never point at different runs.
--
-- 4. `analysis` holds the COMPLETE ScanAnalysis JSON the caller received --
--    not a summary -- because the point of this table is to let the owner see
--    exactly what a specific run answered, including every basis, arc and
--    caveat. `request` holds only what was asked (the typed body, or the
--    photo's content-type/size) -- never image bytes.
--
-- 5. `app_version` is the exact release identity: the deployed package
--    version plus, on Vercel, the git commit SHA, ref, deployment id,
--    environment and URL. A behaviour change in the app is traceable to the
--    exact commit that produced a given row.

create extension if not exists pgcrypto; -- gen_random_uuid, unused here (the app supplies id) but harmless if already present

create table if not exists public.scan_runs (
  id               uuid primary key,                 -- generated by the app before analysis (crypto.randomUUID)
  created_at       timestamptz not null default now(),
  source           text        not null check (source in ('photo', 'manual')),
  status           text        not null,              -- terminal ScanAnalysis.status, or a route-level failure code
  error            text,                              -- ScanAnalysis.error, when the run ended in one
  request          jsonb       not null,               -- request facts/metadata; NEVER image bytes or base64
  analysis         jsonb,                              -- the COMPLETE ScanAnalysis JSON returned to the caller
  app_version      jsonb       not null,               -- { package_version, git_sha, git_ref, deployment_id, vercel_env, url }
  image_bucket     text,                               -- set only for a photo run whose image was stored
  image_path       text,                               -- "<run_id>/original.<ext>" inside image_bucket
  image_mime_type  text,
  image_bytes      bigint,
  image_sha256     text,
  image_status     text        check (image_status in ('stored', 'unavailable', 'failed', 'not_applicable'))
);

comment on table  public.scan_runs               is 'One row per accepted POST /api/scan run (photo or manual). Server-write only; no anon policy, no public read path.';
comment on column public.scan_runs.request       is 'Request facts/metadata only -- for a photo, content_type + size_bytes; for manual, the typed body. Never image bytes or base64.';
comment on column public.scan_runs.analysis      is 'The complete ScanAnalysis JSON as built by analyzeScan/analyzeManual -- not a summary. run_id, app_version and persistence live in their own columns (id, app_version, image_*), and are attached to the HTTP response only.';
comment on column public.scan_runs.app_version   is 'Exact app release identity at the time of the run: package.json version plus Vercel git SHA/ref/deployment/environment/URL where available.';
comment on column public.scan_runs.image_status  is 'stored | unavailable (not configured) | failed | not_applicable (manual run, no image). Never "stored" unless the upload actually succeeded.';

-- The only two ways this table is ever read: newest-first, and filtered by
-- outcome. Both need an index or a growing table makes the SQL editor slow.
create index if not exists scan_runs_created_at_idx on public.scan_runs (created_at desc);
create index if not exists scan_runs_status_idx      on public.scan_runs (status);
create index if not exists scan_runs_source_idx      on public.scan_runs (source);

alter table public.scan_runs enable row level security;

-- Deliberately NO policies. With RLS enabled and no policy, the anon and
-- authenticated roles can do nothing at all; the service role key used by
-- lib/scan-history/store.ts bypasses RLS and is the only way in. Do not add a
-- select policy here -- that is what would turn every scan a stranger ran
-- into public data.

-- The private bucket for original photos. `public = false` is the whole
-- point: no object in this bucket is ever reachable by an unsigned URL, and
-- this app never mints a signed one -- there is no read/download feature.
insert into storage.buckets (id, name, public)
values ('scan-images', 'scan-images', false)
on conflict (id) do nothing;

-- Deliberately NO storage.objects policies for this bucket either. The
-- service role bypasses storage RLS the same way it bypasses table RLS, so an
-- upload/delete from lib/scan-history/store.ts works with no policy at all;
-- adding an anon policy here would be the one line that makes a private
-- bucket readable from a browser.

-- Read one run (including its image's location, not its bytes):
--   select id, created_at, source, status, image_bucket, image_path, image_sha256
--   from public.scan_runs order by created_at desc limit 20;
-- Find every failed run:
--   select id, created_at, source, status, error from public.scan_runs
--   where status not in ('scored', 'not_scored', 'form_not_scored', 'ingredient_not_supported')
--   order by created_at desc;
-- Fetch a stored photo's bytes (service role key required, e.g. from the
-- Supabase dashboard's Storage browser, never from this app):
--   Storage -> scan-images -> <image_path>.
